{% set name = "pystow" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystow-{{ version }}.tar.gz
  sha256: db853bb906ffeb124c6bb20ed99f4594161b6c6c7883f04c2ec593d07897951a

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - click
    - pickle5  # [py<38]
    - python
    - requests
    - tqdm

test:
  imports:
    - pystow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cthoyt/pystow
  summary: Easily pick a place to store data for your python package.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://pystow.readthedocs.io/en/latest/
  dev_url: https://github.com/cthoyt/pystow

extra:
  recipe-maintainers:
    - cthoyt
